// ===== SAINTS: quotes (Orthodox, Catholic, and saints honoured by both). =====
// Add a saint by copying one block and editing it. tradition = "Catholic" | "Orthodox" | "Catholic & Orthodox"
const SAINTS=[
  {"id": "augustine-of-hippo", "name": "Augustine of Hippo", "short": "AUGUSTINE", "dates": "354–430", "tradition": "Catholic", "feast": "August 28 (Catholic) · June 15 (Orthodox, as Blessed Augustine)", "quotes": [{"t": "You have made us for yourself, O Lord, and our heart is restless until it rests in you.", "w": "Confessions, Book I"}, {"t": "Faith is to believe what you do not see; the reward of this faith is to see what you believe.", "w": "Sermon 43"}], "epithet": "Bishop & Doctor of the Church"},
  {"id": "thomas-aquinas", "name": "Thomas Aquinas", "short": "AQUINAS", "dates": "1225–1274", "tradition": "Catholic", "feast": "January 28 (Catholic)", "quotes": [{"t": "Grace does not destroy nature, but perfects it.", "w": "Summa Theologiae I, q.1, a.8"}], "epithet": "Priest & Doctor of the Church"},
  {"id": "anselm-of-canterbury", "name": "Anselm of Canterbury", "short": "ANSELM", "dates": "1033–1109", "tradition": "Catholic", "feast": "April 21 (Catholic)", "quotes": [{"t": "I do not seek to understand that I may believe, but I believe in order to understand.", "w": "Proslogion, chapter 1"}], "epithet": "Archbishop & Doctor of the Church"},
  {"id": "bernard-of-clairvaux", "name": "Bernard of Clairvaux", "short": "BERNARD", "dates": "1090–1153", "tradition": "Catholic", "feast": "August 20 (Catholic)", "quotes": [{"t": "The reason for loving God is God; the measure of love is to love without measure.", "w": "On Loving God"}], "epithet": "Abbot & Doctor of the Church"},
  {"id": "teresa-of-avila", "name": "Teresa of Ávila", "short": "TERESA OF ÁVILA", "dates": "1515–1582", "tradition": "Catholic", "feast": "October 15 (Catholic)", "quotes": [{"t": "Let nothing disturb you, let nothing frighten you. All things pass; God never changes. God alone suffices.", "w": "Her bookmark poem"}], "female": true, "epithet": "Virgin & Doctor of the Church"},
  {"id": "john-henry-newman", "name": "John Henry Newman", "short": "NEWMAN", "dates": "1801–1890", "tradition": "Catholic", "feast": "October 9 (Catholic)", "quotes": [{"t": "To be deep in history is to cease to be Protestant.", "w": "Essay on the Development of Christian Doctrine"}], "epithet": "Priest & Cardinal"},
  {"id": "john-paul-ii", "name": "John Paul II", "short": "JOHN PAUL II", "dates": "1920–2005", "tradition": "Catholic", "feast": "October 22 (Catholic)", "quotes": [{"t": "Faith and reason are like two wings on which the human spirit rises to the contemplation of truth.", "w": "Fides et Ratio, opening line"}], "epithet": "Pope"},
  {"id": "ignatius-of-antioch", "name": "Ignatius of Antioch", "short": "IGNATIUS", "dates": "died c. 108", "tradition": "Catholic & Orthodox", "feast": "October 17 (Catholic) · December 20 (Orthodox)", "quotes": [{"t": "Where Jesus Christ is, there is the Catholic Church.", "w": "Letter to the Smyrnaeans 8"}], "epithet": "Bishop & Martyr"},
  {"id": "irenaeus-of-lyons", "name": "Irenaeus of Lyons", "short": "IRENAEUS", "dates": "c. 130–202", "tradition": "Catholic & Orthodox", "feast": "June 28 (Catholic) · August 23 (Orthodox)", "quotes": [{"t": "The glory of God is a living man; and the life of man is the vision of God.", "w": "Against Heresies IV.20.7"}], "epithet": "Bishop & Father of the Church"},
  {"id": "cyprian-of-carthage", "name": "Cyprian of Carthage", "short": "CYPRIAN", "dates": "c. 200–258", "tradition": "Catholic & Orthodox", "feast": "September 16 (Catholic and Orthodox)", "quotes": [{"t": "He cannot have God for his Father who does not have the Church for his mother.", "w": "On the Unity of the Church 6"}], "epithet": "Bishop & Martyr"},
  {"id": "athanasius-of-alexandria", "name": "Athanasius of Alexandria", "short": "ATHANASIUS", "dates": "c. 296–373", "tradition": "Catholic & Orthodox", "feast": "May 2 (Catholic) · January 18 (Orthodox)", "quotes": [{"t": "He became man that we might become God.", "w": "On the Incarnation 54"}], "epithet": "Archbishop & Confessor"},
  {"id": "gregory-of-nazianzus", "name": "Gregory of Nazianzus", "short": "GREGORY", "dates": "c. 329–390", "tradition": "Catholic & Orthodox", "feast": "January 2 (Catholic) · January 25 (Orthodox)", "quotes": [{"t": "That which He has not assumed He has not healed.", "w": "Letter 101"}], "epithet": "Archbishop & Theologian"},
  {"id": "jerome", "name": "Jerome", "short": "JEROME", "dates": "c. 347–420", "tradition": "Catholic & Orthodox", "feast": "September 30 (Catholic) · June 15 (Orthodox, as Blessed Jerome)", "quotes": [{"t": "Ignorance of Scripture is ignorance of Christ.", "w": "Commentary on Isaiah, Prologue"}], "epithet": "Priest & Doctor of the Church"},
  {"id": "john-chrysostom", "name": "John Chrysostom", "short": "CHRYSOSTOM", "dates": "c. 347–407", "tradition": "Catholic & Orthodox", "feast": "September 13 (Catholic) · November 13 (Orthodox)", "quotes": [{"t": "Do you wish to honour the body of Christ? Do not despise him when he is naked.", "w": "Homily 50 on Matthew"}], "epithet": "Archbishop & Hierarch"},
  {"id": "vincent-of-lerins", "name": "Vincent of Lérins", "short": "VINCENT", "dates": "died c. 445", "tradition": "Catholic & Orthodox", "feast": "May 24 (Catholic and Orthodox)", "quotes": [{"t": "We hold that which has been believed everywhere, always, by all.", "w": "Commonitory 2"}], "epithet": "Monk & Priest"},
  {"id": "isaac-the-syrian", "name": "Isaac the Syrian", "short": "ISAAC", "dates": "7th century", "tradition": "Orthodox", "feast": "January 28 (Orthodox)", "quotes": [{"t": "Be at peace with your own soul, and heaven and earth will be at peace with you.", "w": "Ascetical Homilies"}], "epithet": "Bishop & Ascetic"},
  {"id": "seraphim-of-sarov", "name": "Seraphim of Sarov", "short": "SERAPHIM", "dates": "1754–1833", "tradition": "Orthodox", "feast": "January 2 (Orthodox, Julian calendar)", "quotes": [{"t": "Acquire a peaceful spirit, and thousands around you will be saved.", "w": "Attributed saying"}], "epithet": "Venerable Elder"},
  {"id": "silouan-the-athonite", "name": "Silouan the Athonite", "short": "SILOUAN", "dates": "1866–1938", "tradition": "Orthodox", "feast": "September 24 (Orthodox)", "quotes": [{"t": "Keep your mind in hell, and despair not.", "w": "Words recorded by Elder Sophrony"}], "epithet": "Venerable Elder"},
  {"id": "basil-the-great", "name": "Basil the Great", "short": "BASIL", "dates": "c. 330–379", "tradition": "Catholic & Orthodox", "feast": "January 2 (Catholic) · January 1 (Orthodox)", "epithet": "Archbishop & Hierarch", "quotes": [{"t": "The bread in your cupboard belongs to the hungry; the coat in your closet belongs to the one who needs it.", "w": "Homily on Luke 12:18 (paraphrased)"}]},
  {"id": "francis-of-assisi", "name": "Francis of Assisi", "short": "FRANCIS", "dates": "1181–1226", "tradition": "Catholic", "feast": "October 4 (Catholic)", "epithet": "Friar & Founder", "quotes": [{"t": "Where there is charity and wisdom, there is neither fear nor ignorance.", "w": "Admonitions 27"}]}
];
